### ISSUE TITLE
some classes have spells from other classes

### ISSUE THREAD

**Issue by diluh** [azerothcore/mod-arac#1]
![image](https://user-images.githubusercontent.com/46387591/73433696-f9146080-4323-11ea-97ff-ffbe7c4b30f3.png)

![image](https://user-images.githubusercontent.com/46387591/73433814-40025600-4324-11ea-8e6f-198a5cb77938.png)

@iThorgrim-hub @Helias

**Comment by iThorgrim-hub** [comment]
I've just fixed it and I'll push a new version as soon as I can :)

**Comment by iThorgrim-hub** [comment]
It's upload & Fix :) I close this issues, Thanks for report :D
