### ISSUE TITLE
Code removed?

### ISSUE THREAD

**Issue by MatthewHinds** [azerothcore/mod-arac#12]
Hi there, I noticed that the releases contain an empty project and any links to the original repo now 404s.
Only reference I can see is a google cache: https://webcache.googleusercontent.com/search?q=cache:FyKvTSvsvgUJ:https://github.com/iThorgrim-hub/mod-arac/releases+&cd=1&hl=en&ct=clnk&gl=nz

Does anyone have the latest copy of the module?

**Comment by benjymansy123** [comment]
https://github.com/benjymansy123/iThorgrim-Backup/releases/tag/backup

**Comment by Helias** [comment]
would be great if you could make a PR here to update this module
