### ISSUE TITLE
Non-BE Horde Paladin needs Level 12 Quest!

### ISSUE THREAD

**Issue by ValeTheVioletMote** [azerothcore/mod-arac#2]
Knight-Lord Bloodvalor should offer https://wowwiki.fandom.com/wiki/Quest:The_First_Trial and its chain to a level 12 Horde paladin.

Not having this quest available bars the Paladin from learning Redemption.

**Comment by iThorgrim-Hub** [comment]
It's now fix for all of Class Quest
