### ISSUE TITLE
(Core/Cosmetic): On player create an item does not appear for the class hunter.

### ISSUE THREAD

**Issue by Tyrelis** [azerothcore/mod-arac#4]
##### SMALL DESCRIPTION:
The player shirt is missing for hunter class human/undead.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
On the player creation page when you create a hunter human or undead of either gender the character shirt item 148(Rugged Trapper's Shirt) should appear on character creation page as well after character is created.

##### CURRENT BEHAVIOUR:
On the player creation page when you create a hunter human or undead of either gender the character shirt is missing item 148(Rugged Trapper's Shirt) but appears after the character has been created.

##### STEPS TO REPRODUCE THE PROBLEM:

1. login into the game
2. create a male or female hunter human/undead.
3. The shirt item 148(Rugged Trapper's Shirt) does not appear in creation screen.
4. It appears after character is created though.

##### EXTRA NOTES:
It seems to be a dbc file issue looked in database and nothing is indicating that the items are missing on character creation page.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
#8b7530b

##### OPERATING SYSTEM:

Ubuntu 18.04

##### MODULES:
All classes all races

##### OTHER CUSTOMIZATIONS:

None

**Comment by Open-Wow** [comment]
It's Fixed ! :D
https://github.com/Open-Wow/mod-arac

**Comment by Tyrelis** [comment]
Not fixed it even worse.

**Comment by Tyrelis** [comment]
The fix works thank you.
