### ISSUE TITLE
playercreateinfo_spell table

### ISSUE THREAD

**Issue by swbuza** [azerothcore/mod-arac#9]
The acore_world database does not appear to have a table called playercreateinfo_spell. Should this table be created, or is it deprecated and the data in playercreateinfo_spell.sql should go somewhere else?

**Comment by FrancescoBorzi** [comment]
@swbuza what version of AC are you using? also [make sure your DB is up to date](https://stackoverflow.com/questions/55282167/how-to-make-sure-that-the-db-is-up-to-date)

**Comment by swbuza** [comment]
I just compiled the server from git clone source for the very first time
two days ago. The database is set to automatically update. According to the
version table in the acore_world database, I am running core_revision
2a6bc1dec0e8 and db_version ACDB 335.4-dev.  So it's all brand new, latest,
as far as I know.

Server has been working fine. Created test characters without that table
existing. So, it's kind of strange.  I did create the table manually and
your mod seems to be working.

**Comment by swbuza** [comment]
It is worth noting that the table (playercreateinfo_spell) does not exist
in the wiki documentation found here:
https://www.azerothcore.org/wiki/database-world

**Comment by LordArcanine** [comment]
ac team maybe renamed it long ago to playercreateinfo_skill, they have almost the same structure, but if you modify the querys to work on that table , when the server start give thousands of errors skipping almost all the errors

**Comment by swbuza** [comment]
If you mean playercreateinfo_skills, then a search-replace of playercreateinfo_spell to playercreateinfo_skills almost works, except it won't run because the queries have the wrong number of columns for that table. One would need to manually add a skill rank value into every single line of the file first.

**Comment by swbuza** [comment]
Unfortunately, even that didn't work. The world server reports every line item as an invalid skill number.

**Comment by LordArcanine** [comment]
i repaired the skill, the items but i still have a problem, the core report that blood elf and draenei racials cant be recognized and skip it, but even if they arent on the playercreateinfo_skill that races receive the skill if they use there old classes, so as i see the core is the one giving them the racials not the sql table

**Comment by Steyfix** [comment]
hello a patch available for the sql query? thank you.

**Comment by drunkenphatkid** [comment]
I was able to replace playercreateinfo_spell with playercreateinfo_cast_spell to match the acore database my new system had.
